version: "3.7"
services:
  app:
    build: .
    restart: always
    ports:
      - "6020:8080"


# docker network create --driver bridge bithumb-backend-net
#networks:
#  default:
#    external:
#      name: bithumb-backend-net

