# Spring Cloud Gateway port
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.38.23.41:6020/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - "gateway"
#  endpoint:
#    gateway:
#      enabled: true

spring:
  cloud:
    gateway:
      # Gateway 공통 필터
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      # MSA 라우팅 정의
      # ID, 목적지(uri), 조건(Predicate), 필터로 구성된다.
      routes:
#        - id: user-service
#          uri: lb://USER
#          predicates:
#            - Path=/users/**
#          filters:
#            - name: UserFilter
#              args:
#                baseMessage: Taeu UserFilter
#                preLogger: true
#                postLogger: true

        - id: auth-service
          uri: lb://USER
          predicates:
            - Path=/auth/**
          filters:
            - name: GlobalFilter
              args:
                baseMessage: Taeu GlobalFilter
                preLogger: true
                postLogger: true


  application:
    name: API-GATEWAY

token:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK